### ISSUE TITLE
bug: PluginConfigId is not assign to the route in case upstreams used instead of the backends

### ISSUE THREAD

**Issue by ikatlinsky** [apache/apisix-ingress-controller#1577]
### Issue description

I am using the ingress controller to create the following apisix resources:
- Plugin configs
- Upstream
- Route

The following definitions are used:

```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: httpbin-upstream
  namespace: acl
spec:
  externalNodes:
  - type: Domain
    name: httpbin.org
  retries: 3
  timeout:
    connect: "3s"
    send: "2s"
    read: "3s"
  loadbalancer:
    type: roundrobin
  healthCheck:
    active:
      concurrency: 10
      host: httpbin.org
      type: http
      timeout: 2
      httpPath: /
      healthy:
        httpCodes:
          - 200
          - 302
        interval: "1s"
        successes: 3
      unhealthy:
        httpCodes:
          - 429
          - 404
          - 500
          - 501
          - 502
          - 503
          - 504
          - 505
        httpFailures: 5
        interval: "3s"
        tcpFailures: 2
        timeouts: 3
---
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: httpbin-plugins
  namespace: acl
spec:
  plugins:
  - name: proxy-rewrite
    enable: true
    config:
      regex_uri:
      - "^/httpbin/(.*)"
      - "/$1"
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpbin-route
  namespace: acl
spec:
  http:
    - name: httpbin-route-rule
      match:
        hosts:
          - apisix.local.net
        paths:
          - /httpbin/*
        methods:
          - GET
      upstreams:
        - name: httpbin-upstream
      plugin_config_name: httpbin-plugins
```

As result my configuration is applied to the apisix, but plugin config is not assigned to the route. 
My assumption that issue is because of the bug in the following file: apisix_route.go, more precisely the following fragment

```go
if part.PluginConfigName != "" {
				route.PluginConfigId = id.GenID(apisixv1.ComposePluginConfigName(ar.Namespace, part.PluginConfigName))
			}
```

is only executed when `len(backends) > 0` (function translateHTTPRouteV2).

I guess it should be applied both for case with backends and case with upstream, like mine.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long): 1.6.0
- your Kubernetes cluster version (output of kubectl version): 1.23.6

### Minimal test code / Steps to reproduce

1. Apply the definitions which are provided above
2. Wait till definitions will be applied
3. Check resulted configuration of the route

### Actual result

```json
{
  "uris": [
    "/httpbin/*"
  ],
  "name": "acl_httpbin-route_httpbin-route-rule",
  "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
  "methods": [
    "GET"
  ],
  "hosts": [
    "apisix.local.net"
  ],
  "upstream_id": "6f1d84e5",
  "labels": {
    "managed-by": "apisix-ingress-controller"
  },
  "status": 1
}
```

plugin_config_id is missed from the configuration

### Error log

no error log, just incorrect behaviour

### Expected result

plugin_config_id is properly assigned to the route

**Comment by ikatlinsky** [comment]
@tao12345666333 created a PR that should fix the problem, described above - https://github.com/apache/apisix-ingress-controller/pull/1578, I hope that will help. Tell me if there are any issues or questions regarding the proposed changes.

**Comment by tao12345666333** [comment]
Thanks! I will add comments in #1578

**Comment by tao12345666333** [comment]
It has been resolved. I will close this one, thanks

**Comment by renatomattos2912** [comment]
> It has been resolved. I will close this one, thanks

Hello tao, im trying to update my controller to get this fix, but the latest image in docker repo for ingress controller is 1.6.0 and it is still not working for this bug here. It is planned to be in 1.6.1 or any future docker image for ingresso controller?
