### ISSUE TITLE
bug: Routing configuration not taking effect, and the backend reports an etcd error.

### ISSUE THREAD

**Issue by wumengchao** [apache/apisix-ingress-controller#2071]
### Current Behavior

Occasionally, changes to the routing configuration do not take effect, and the deleted routing configurations are still active. At the same time, the backend reports the following errors, and I am not sure if these errors are related to this bug.

2023-11-25T04:31:57+08:00 [31merror[0m adapter/etcd.go:141 failed to create object, ignore it{error 26 0 rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request} {revision 11 26 <nil>} {key 15 0 /apisix/routes/6d611fe0 <nil>}

### Error Logs

2023-11-25T04:31:57+08:00 [31merror[0m adapter/etcd.go:141 failed to create object, ignore it{error 26 0 rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request} {revision 11 26 <nil>} {key 15 0 /apisix/routes/6d611fe0 <nil>}

### Steps to Reproduce

Deployed using the latest version 1.7.1, through the Composite Architecture method.

### Environment

- APISIX Ingress controller version (apisix-ingress-controller 1.7.1)
- Kubernetes cluster version (1.20.6) tke
- OS version if running APISIX Ingress controller in a bare-metal environment (Linux VM-1-200-tlinux 4.14.105-19-0020.1 #1 SMP Fri Apr 23 10:22:59 CST 2021 x86_64 x86_64 x86_64 GNU/Linux) tos

**Comment by Revolyssup** [comment]
@wumengchao What are the logs from Ingress when you apply the configuration which doesn't take effect?

**Comment by wumengchao** [comment]
> @wumengchao当您应用未生效的配置时，Ingress 的日志是什么？

2023-11-28T09:55:18+08:00 [31merror[0m adapter/etcd.go:141 failed to create object, ignore it{error 26 0 rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request} {revision 11 354 <nil>} {key 15 0 /apisix/routes/35232d71 <nil>}

I have launched 15 pods.

**Comment by wumengchao** [comment]
From the logs, it appears that an error is reported every 5 minutes.

**Comment by wumengchao** [comment]
Today, it was also discovered that some pods remain in the "create object" state during the startup process, and all access attempts to enter these pods result in a 404 error with the message {"error_msg":"404 Route Not Found"}.

The last log entry is: adapter/etcd.go:147 created object{revision 11 126 <nil>} {key 15 0 /apisix/routes/ac8106c4 <nil>}

s there a probe that can detect whether the route object has been successfully created?

**Comment by Revolyssup** [comment]
Looking into this...

**Comment by Revolyssup** [comment]
@wumengchao something like this
![Uploading Screenshot 2023-11-29 at 2.33.34 PM.png…]()

**Comment by Revolyssup** [comment]
something like this
<img width="1044" alt="Screenshot 2023-11-29 at 2 33 34 PM" src="https://github.com/apache/apisix-ingress-controller/assets/43276904/ae34f716-762f-44ae-9dcc-5e853c2a1a15">
<img width="1512" alt="Screenshot 2023-11-29 at 2 34 00 PM" src="https://github.com/apache/apisix-ingress-controller/assets/43276904/93c321f4-e26e-416b-92d4-d6b338f77bb4">

**Comment by wumengchao** [comment]
15 pods refer to ingress-apisix-composite.
When the pod routing configuration became invalid, I connected to the problematic pod's 12379 port using etcdkeeper and found that the data was normal.At this point, the only way to recover was to delete the route and then rebuild it. I tried deleting the pod and creating a new one, but it was ineffective. I changed the deployment to a DaemonSet.

**Comment by wumengchao** [comment]
I intentionally configured an incorrect path. After encountering "failed to find route in cache," the following error immediately appears: "failed to create object, ignore it{error 26 0 rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request} {revision 11 76 <nil>} {key 15 0 /apisix/routes/eff2f3e2 <nil>}".

**Comment by wumengchao** [comment]
“failed to create object, ignore it{error 26 0 rpc error: code = InvalidArgument ”
How can one find an InvalidArgument?

**Comment by Revolyssup** [comment]
@wumengchao A similar issue with reproduction steps has been reported here - https://github.com/apache/apisix-ingress-controller/issues/2076. I am working on this,

**Comment by Revolyssup** [comment]
fixed by https://github.com/apache/apisix-ingress-controller/pull/2078

**Comment by wumengchao** [comment]
After compiling and releasing the master branch, the issue still persists.

**Comment by Revolyssup** [comment]
@wumengchao Same errors?

**Comment by wumengchao** [comment]
> @wumengchao Same errors?

yes. This is a screenshot after compilation.
![image](https://github.com/apache/apisix-ingress-controller/assets/14342500/f391602a-933b-47cd-98d7-f3a3af83afc9)

**Comment by wumengchao** [comment]
This is a screenshot of the error message.
![image](https://github.com/apache/apisix-ingress-controller/assets/14342500/446613a5-b331-4c65-a5a5-0a18914e70cb)

**Comment by wumengchao** [comment]
I deliberately made incorrect changes to the routing configuration, such as the service name or port, and then changed it back to normal. This issue can be reproduced immediately.
![image](https://github.com/apache/apisix-ingress-controller/assets/14342500/6fa1c404-4071-4a44-965a-2833493dfab2)

**Comment by Revolyssup** [comment]
@wumengchao Actually the error here is to be ignored. As you can see, in the very next line the object actually gets created. If you delete and recreate, you will see this ignora-able error.

**Comment by Revolyssup** [comment]
@wumengchao Yes this log can be ignored. I can confirm that the latest master doesn't have this bug.
I followed the following repro steps.
- Build the image on master
- deployed samples/deploy/composite.yml (with my image)
- created wrong route then corrected it, it was updated in apisix successfully. Similarly deleted and created again, same thing happened.

**Comment by wumengchao** [comment]
OK

**Comment by damoshushu** [comment]
hello @Revolyssup ,
I still get this issue 

` kubectl -n apisix get pods apisix-7bc4f47f47-gcvws -o yaml | grep image -C 4
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: apache/apisix-ingress-controller:1.8.2
    imagePullPolicy: IfNotPresent`

logs:
`2024-06-26T16:41:13+08:00	info	adapter/etcd.go:147	created object{revision 11 27  <nil>} {key 15 0 /apisix/routes/d19e6f8f <nil>}
2024-06-26T16:41:13+08:00	info	adapter/etcd.go:147	created object{revision 11 28  <nil>} {key 15 0 /apisix/upstreams/4405a246 <nil>}
2024-06-26T16:41:13+08:00	info	adapter/etcd.go:147	created object{revision 11 29  <nil>} {key 15 0 /apisix/plugin_configs/6b2eb039 <nil>}
2024-06-26T16:41:13+08:00	info	adapter/etcd.go:147	created object{revision 11 30  <nil>} {key 15 0 /apisix/routes/8659c925 <nil>}
2024-06-26T16:41:13+08:00	error	adapter/etcd.go:141	failed to create object, ignore it{error 26 0  rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request} {revision 11 30  <nil>} {key 15 0 /apisix/upstreams/4405a246 <nil>}
2024-06-26T16:41:13+08:00	info	adapter/etcd.go:147	created object{revision 11 31  <nil>} {key 15 0 /apisix/routes/2d3cc270 <nil>}
`

**Comment by boscard** [comment]
@Revolyssup I've tested this with versions `1.7.0`, `1.7.1`, `1.8.0`, `1.8.1` and `1.8.2` and ApiSix version `3.9.1` and I'm always getting the same errors:

```
2024-08-02T22:19:38+08:00       error   adapter/etcd.go:141     failed to create object, ignore it{error 26 0  rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request} {revision 11 115  <nil>} {key 15 0 /apisix/upstreams/5c607e35 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 116  <nil>} {key 15 0 /apisix/routes/ebba555c <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 117  <nil>} {key 15 0 /apisix/routes/a08b23a9 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 118  <nil>} {key 15 0 /apisix/ssls/1aaae1cf <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 119  <nil>} {key 15 0 /apisix/upstreams/133835d9 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 120  <nil>} {key 15 0 /apisix/routes/87d32b8f <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 121  <nil>} {key 15 0 /apisix/ssls/15c53338 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 122  <nil>} {key 15 0 /apisix/upstreams/e673e843 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 123  <nil>} {key 15 0 /apisix/routes/b8a67001 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 124  <nil>} {key 15 0 /apisix/ssls/9e952c6f <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 125  <nil>} {key 15 0 /apisix/upstreams/d561e564 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 126  <nil>} {key 15 0 /apisix/routes/24f80351 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 127  <nil>} {key 15 0 /apisix/ssls/ad479896 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 128  <nil>} {key 15 0 /apisix/upstreams/d7275b3d <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 129  <nil>} {key 15 0 /apisix/routes/2270db75 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 130  <nil>} {key 15 0 /apisix/ssls/d1c3f9a3 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 131  <nil>} {key 15 0 /apisix/upstreams/8b2bcb52 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 132  <nil>} {key 15 0 /apisix/routes/7220df47 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 133  <nil>} {key 15 0 /apisix/routes/46a46b3e <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 134  <nil>} {key 15 0 /apisix/routes/d77bd714 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 135  <nil>} {key 15 0 /apisix/routes/a2e2c60a <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 136  <nil>} {key 15 0 /apisix/routes/d64f4c89 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 137  <nil>} {key 15 0 /apisix/routes/adf55859 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 138  <nil>} {key 15 0 /apisix/ssls/792ba877 <nil>}
2024-08-02T22:19:38+08:00       error   adapter/etcd.go:141     failed to create object, ignore it{error 26 0  rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request} {revision 11 138  <nil>} {key 15 0 /apisix/upstreams/8b2bcb52 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 139  <nil>} {key 15 0 /apisix/routes/c3caca1d <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 140  <nil>} {key 15 0 /apisix/ssls/6c28a184 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 141  <nil>} {key 15 0 /apisix/upstreams/51554a79 <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 142  <nil>} {key 15 0 /apisix/routes/6f69657d <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 143  <nil>} {key 15 0 /apisix/ssls/ac2bf411 <nil>}
2024-08-02T22:19:38+08:00       error   adapter/etcd.go:141     failed to create object, ignore it{error 26 0  rpc error: code = InvalidArgument desc = etcdserver: duplicate key given in txn request} {revision 11 143  <nil>} {key 15 0 /apisix/upstreams/65afa96b <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:147     created object{revision 11 144  <nil>} {key 15 0 /apisix/routes/964b0c6a <nil>}
2024-08-02T22:19:38+08:00       info    adapter/etcd.go:185     updated object{revision 11 145  <nil>} {key 15 0 /apisix/ssls/d7f19a17 <nil>}
```
I can help with debugging if needed.

**Comment by rknightion** [comment]
We're getting the same over in https://github.com/apache/apisix-ingress-controller/issues/2276 (also using apisixtls resources)
