### ISSUE TITLE
help request: Datadog plugin config - can't define DogStatsD target with CRDs

### ISSUE THREAD

**Issue by swo-ralf** [apache/apisix-ingress-controller#2125]
### Description

First, a happy new year to everyone :)

Follow up for apache/apisix#10473. As discussed there, I tried the approach with defining a K8s service for the DogStatsD DaemonSet but still I only see in the logs, that the local host is tried to be reached:

`2024/01/03 09:41:39 [error] 49#49: *3894 [lua] datadog.lua:143: send_metric_over_udp(): failed to report request latency to dogstatsd server: host[127.0.0.1] port[8125] err: connection refused, context: ngx.timer, client: 10.224.0.5, server: 0.0.0.0:9080`

My used service:
```
kind: Service
apiVersion: v1
metadata:
  name: dogstatsd-service
  namespace: datadog
spec:
  selector:
    app.kubernetes.io/instance: datadog-agent
  ports:
  - protocol: UDP
    port: 8125
    targetPort: 8125
```

And the following Apisix plugin config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-metadata-config-map
  namespace: ingress-apisix
data:
  config.yaml: |
    - cluster: <kubernetes cluster name>
      plugins:
      - name: datadog
        metadata:
          host: "dogstatsd-service.datadog.svc.cluster.local"
          port: 8125
          namespace: "datadog"
```

I tried also with cluster name default, no change. Also with dedicated global rule, but it didn't make change. Also using the cluster ip of the created service as host didn't make any change.
```
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: global
spec:
  plugins:
  - name: datadog
    enable: true
    config:
      host: "dogstatsd-service.datadog.svc.cluster.local"
      port: 8125
      namespace: "datadog"
      constant_tags: ["source:apisix"]
```

Little namespace overview:
- datadog: place of Datadog installation and created service for the DogStatsD DaemonSet
- ingress-apisix: place of Apisix installation

@Revolyssup I hope you have an idea.

Thanks for the support!

### Environment

AKS 1.27.3
Apisix chart 1.7.1
Apisix: 3.6.0
DataDog Operator 1.2.0 with DataDog Agent 3.47
DataDog Agent runs on each AKS node, DogStatsD host port is default and exposed (at least I see it correctly in the POD YAMl description).

**Comment by Revolyssup** [comment]
> plugin-metadata-config-map

Will you also try removing the `namespace: ingress-apisix` from configmap

**Comment by swo-ralf** [comment]
@Revolyssup tried it without namespace and see the following error in log:

`2024-01-05T10:40:12+08:00	[31merror[0m	apisix/pluginconfig.go:139	failed to create pluginConfig: unexpected status code 400; error message: {"error_msg":"invalid configuration: additional properties forbidden, found name"}`

Which I do not understand, because [https://github.com/apache/apisix-ingress-controller/blob/7a9a0fab478861ed3a90f0793a65100ace9de047/conf/plugin-metadata-config-map.yaml](url) shows exactly the same thing.

**Comment by Revolyssup** [comment]
@swo-ralf This has been fixed in apisix 3.7.0. Use apisix version 3.7.0>= please

**Comment by Revolyssup** [comment]
This was fixed here https://github.com/apache/apisix/pull/10315

**Comment by swo-ralf** [comment]
I updated today to Apisix chart 1.10.0 and have Apisix 3.8.0 running and still see no change.
The last reported error with invalid config is fixed, but still host doesn't get changed away from localhost.

`2024/01/22 09:38:15 [error] 49#49: *13349 [lua] datadog.lua:143: send_metric_over_udp(): failed to report request latency to dogstatsd server: host[127.0.0.1] port[8125] err: connection refused, context: ngx.timer, client: 10.224.0.4, server: 0.0.0.0:9080`

Doesn't make a difference if I provide the plugin-metadata-config-map in the apisix namespace or omitting the namespace completely.

@Revolyssup What kind of information would be additional helpful to pinpoint the issue?

Thanks!

**Comment by redhandpl** [comment]
HI,
I'm using Apisix chart 2.8.1 with Apisix 3.9.1 and still cannot created metadata for DataDog plugin.

`apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  name: global
spec:
  plugins:
  - name: datadog
    enable: true
    config:
      host: "datadog-agent.datadog.svc.cluster.local"
      port: 8125
      namespace: "apisix"`

This adds global rule
`❯ curl "http://127.0.0.1:9180/apisix/admin/global_rules/" -H 'X-API-KEY: THEKEY'
{"total":1,"list":[{"key":"/apisix/global_rules/cd935c2f","value":{"id":"cd935c2f","plugins":{"datadog":{"port":8125,"prefer_name":true,"buffer_duration":60,"inactive_timeout":5,"retry_delay":1,"namespace":"apisix","name":"datadog","batch_max_size":1000,"max_retry_count":0,"host":"datadog-agent.datadog.svc.cluster.local"}},"create_time":1720782046,"update_time":1720783721},"modifiedIndex":641,"createdIndex":488}]}`

But not the metedata
`❯ curl http://127.0.0.1:9180/apisix/admin/plugin_metadata/ -H 'X-API-KEY: THEKEY'
{"total":0,"list":[]}`

And in logs I still see
`2024/07/12 11:36:22 [error] 51#51: *6297 [lua] datadog.lua:172: send_metric_over_udp(): failed to report req body size to dogstatsd server: host[127.0.0.1] port[8125] err: connection refused, context: ngx.timer, client: 10.103.10.44, server: 0.0.0.0:9080
`

Adding plugin-metadata-config-map, does not make any difference
`apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-metadata-config-map
data:
  config.yaml: |
    - cluster: default
      plugins:
      - name: datadog
        metadata:
          host: "datadog-agent.datadog.svc.cluster.local"
          port: 8125
          namespace: "apisix"`

**Comment by mfractal** [comment]
Exact same problem here. Using apisix 3.9.1 with chart 2.8.1 too. 

datadog plugin ignores ApisixPluginConfig and ApisixGlobalRule settings.
